spring.application.name=pethome

# Base de datos (Neon)
spring.datasource.url=jdbc:postgresql://ep-icy-wind-ax1xammn-pooler.c-4.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=${DB_PASSWORD}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false